export type Verdict = 'legal' | 'illegal'

export interface RightCard {
  id: string
  /** The bold scenario shown on the front of the card, phrased as a yes/no judgement. */
  scenario: string
  /** The correct answer: is the described action legal (compliant) or illegal? */
  verdict: Verdict
  /** The precise law that applies, e.g. "Section 130, Motor Vehicles Act". */
  law: string
  /** A quick, conversational 2-sentence rule explaining what to do. */
  rule: string
  /** A short visual illustration prompt (used by the AI ingestor output). */
  illustrationPrompt?: string
  /** 2-3 keyword prompt used to render the scenario banner image. */
  imageKeyword?: string
  /** The category this card belongs to (from the AI generator). */
  category?: string
  /** Marks cards that were generated by the AI Card Ingestor. */
  generated?: boolean
}

/* ---------- AI Card Ingestor (condense + fact-check) ---------- */

export type LegitimacyStatus = 'VERIFIED_LAW' | 'BUSTED_MYTH' | 'CRIMINAL_VIOLATION'

export interface IngestedCard {
  /** Ultra-condensed 10-15 word dramatic scenario statement. */
  scenario: string
  /** Word count of the scenario (enforced to 10-15). */
  wordCount: number
  /** Whether the described action is lawful/compliant. */
  isLegal: boolean
  /** Whether the claim is real law, a debunked myth, or a gray area. */
  legitimacyStatus: LegitimacyStatus
  /** Human-readable legitimacy tag, e.g. "Debunked Legal Myth". */
  legitimacyLabel: string
  /** The precise statute/section mapped to the scenario. */
  mappedLaw: string
  /** 1-2 sentence rule explaining the right and what to do. */
  shortExplanation: string
  /** Short category bucket, e.g. "Arrest & Police Rights". */
  category: string
}

export type PackId =
  | 'traffic'
  | 'tenant'
  | 'consumer'
  | 'arrest'
  | 'ingested'

export interface Pack {
  id: PackId
  name: string
  tagline: string
  /** lucide-react icon name resolved in the UI. */
  icon: string
  /** two-stop gradient used for the pack's cards, as tailwind color values. */
  gradient: [string, string]
  cards: RightCard[]
}

/* ---------- Hazard Reflex live simulation ---------- */

export type ReflexTone = 'harsh' | 'medium' | 'lawful'

export interface ReflexPreset {
  tone: ReflexTone
  label: string
  text: string
}

export interface ReflexScenario {
  id: string
  title: string
  /** short status tag, e.g. "POLICE STOP" */
  tag: string
  prompt: string
  presets: ReflexPreset[]
}

export type ReflexVerdict = 'CRITICAL' | 'TRAP' | 'SHIELD'

export interface ReflexReport {
  verdictType: ReflexVerdict
  verdictTitle: string
  /** 0-100 legal liability/risk score */
  liabilityScore: number
  whatWentWrong: string[]
  whatYouShouldDo: string[]
  exactWordsToSay: string
  applicableLaw: string
}
